#!/usr/bin/env python3
"""
Source 10: Executor Adapter Training Data

Two data types:
  A) Command correction  — bad command + stderr + help excerpt  →  corrected command + reasoning
  B) Output filtering    — noisy raw tool output  →  filtered findings only

Data is generated by:
  1. Detecting which pentest tools are actually installed (shutil.which)
  2. Capturing their real --help text as ground truth
  3. Using GPT to synthesise realistic mistakes + corrections for each tool
  4. Using GPT to synthesise realistic noisy outputs + filtered findings

Target: 2000 examples (1400 correction, 600 filtering)

Usage:
  python3 src/source10_executor.py --test            # 3 examples, no file writes
  python3 src/source10_executor.py --list-categories # show installed tools + counts
  python3 src/source10_executor.py                   # full run
  python3 src/source10_executor.py --type correction # only type-A
  python3 src/source10_executor.py --type filtering  # only type-B
"""

import os
import re
import json
import shutil
import subprocess
import time
import random
import argparse
import threading
from pathlib import Path
from concurrent.futures import ThreadPoolExecutor, as_completed

from openai import OpenAI
from tqdm import tqdm
from dotenv import load_dotenv

import sys as _sys, os as _os
_sys.path.insert(0, _os.path.dirname(_os.path.dirname(_os.path.abspath(__file__))))
from prompts import EXECUTOR_CORRECTION as SYSTEM_CORRECTION, EXECUTOR_FILTERING as SYSTEM_FILTERING


load_dotenv()

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------
OUTPUT_CORRECTION = "raw/executor_correction.jsonl"
OUTPUT_FILTERING  = "raw/executor_filtering.jsonl"
CACHE_DIR         = "raw/.executor_cache"
DEFAULT_WORKERS   = 4
API_DELAY         = 0.2

TARGET_CORRECTION  = 1400
TARGET_FILTERING   = 600
EXAMPLES_PER_TOOL  = 20   # correction pairs per installed tool
FILTER_PER_TOOL    = 8    # filtering examples per tool

# Full catalogue — checked against PATH at runtime
PENTEST_TOOLS = [
    "nmap", "subfinder", "httpx", "ffuf", "gobuster", "nikto",
    "sqlmap", "curl", "wget", "amass", "nuclei", "feroxbuster",
    "wfuzz", "dirb", "masscan", "whatweb", "wafw00f", "theHarvester",
    "dnsx", "naabu", "katana", "gau", "waybackurls", "hakrawler",
    "arjun", "dalfox", "wpscan", "jq", "python3", "nc",
    "rustscan", "enum4linux", "smbclient", "dig", "whois",
    "jwt_tool", "sslyze", "testssl.sh", "crackmapexec",
]



CORRECTION_GEN_PROMPT = """\
You are building a training dataset for a command-correction AI.

Tool: {tool}
Help text (excerpt):
---
{help_text}
---

Generate {n} realistic mistake/correction pairs for this tool. Each pair must be a JSON object:
{{
  "mistake_type": "wrong_flag | missing_arg | wrong_syntax | deprecated_flag | wrong_order",
  "bad_command": "<command with the mistake>",
  "stderr": "<realistic error message the tool would print>",
  "thought": "<3-4 sentence reasoning about what went wrong and how to fix it>",
  "corrected": "<the correct command>"
}}

Rules:
- bad_command must look like something a user would plausibly type
- stderr must match the tool's actual error style (from the help text)
- Use real flags from the help text — do not invent flags
- Target realistic use cases: scanning, enumeration, exploitation, fuzzing
- Return a JSON array of {n} objects, nothing else.
"""

FILTERING_GEN_PROMPT = """\
You are building a training dataset for an output-filtering AI.

Tool: {tool}
Typical use: {use_case}

Generate {n} examples of realistic tool output that needs filtering. Each example:
{{
  "raw_output": "<20-60 lines of realistic, noisy output including progress bars, repeated lines, ANSI codes described as [ANSI], timing info, and 3-8 actual findings mixed in>",
  "filtered_findings": "<only the meaningful lines: found hosts/ports/paths/vulns, one per line>",
  "summary": "<one sentence: what was found>"
}}

Rules:
- raw_output must be realistic — include noise like '::progress:: 45% [ETA 00:03:21]' or repeated banner lines
- filtered_findings must preserve exact finding lines from raw_output (do not paraphrase)
- Mix severity: some examples have 0 findings, some have many
- Return a JSON array of {n} objects, nothing else.
"""

TOOL_USE_CASES = {
    "nmap":         "port and service discovery",
    "subfinder":    "passive subdomain enumeration",
    "httpx":        "HTTP probing and web service discovery",
    "ffuf":         "web directory and parameter fuzzing",
    "gobuster":     "web directory brute-forcing",
    "nikto":        "web server vulnerability scanning",
    "sqlmap":       "SQL injection detection",
    "amass":        "subdomain enumeration via OSINT",
    "nuclei":       "vulnerability template scanning",
    "feroxbuster":  "recursive web content discovery",
    "wfuzz":        "web fuzzing for params and paths",
    "masscan":      "high-speed port scanning",
    "whatweb":      "web technology fingerprinting",
    "wafw00f":      "WAF detection",
    "theHarvester": "email and subdomain OSINT",
    "dnsx":         "DNS resolution and bruteforce",
    "naabu":        "port scanning",
    "katana":       "web crawling",
    "gau":          "historical URL discovery",
    "dalfox":       "XSS parameter analysis",
    "wpscan":       "WordPress vulnerability scanning",
    "sslyze":       "SSL/TLS configuration analysis",
    "enum4linux":   "SMB/AD enumeration",
    "crackmapexec": "Active Directory attack automation",
    "arjun":        "hidden HTTP parameter discovery",
    "jwt_tool":     "JWT token analysis and attacks",
    "curl":         "HTTP request crafting",
    "sqlmap":       "SQL injection exploitation",
}

_gpt_lock = threading.Lock()
client = OpenAI()


def _gpt(prompt: str, max_tokens: int = 2000, model: str = "gpt-4o-mini") -> str:
    with _gpt_lock:
        time.sleep(API_DELAY)
    resp = client.chat.completions.create(
        model=model,
        messages=[{"role": "user", "content": prompt}],
        max_tokens=max_tokens,
        temperature=0.85,
    )
    return resp.choices[0].message.content.strip()


# ---------------------------------------------------------------------------
# Tool detection + help capture
# ---------------------------------------------------------------------------
def detect_installed_tools() -> list[str]:
    return [t for t in PENTEST_TOOLS if shutil.which(t)]


def fetch_help(tool: str) -> str:
    """Capture --help output; fall back to -h; truncate to 3000 chars."""
    cache_path = Path(CACHE_DIR) / f"{tool}.help"
    if cache_path.exists():
        return cache_path.read_text()

    Path(CACHE_DIR).mkdir(parents=True, exist_ok=True)
    text = ""
    for flag in ["--help", "-h", "help"]:
        try:
            r = subprocess.run(
                [tool, flag],
                capture_output=True, text=True, timeout=10
            )
            out = (r.stdout + r.stderr).strip()
            if len(out) > 100:
                text = out[:3000]
                break
        except Exception:
            continue

    cache_path.write_text(text)
    return text


# ---------------------------------------------------------------------------
# Generation helpers
# ---------------------------------------------------------------------------
def _parse_json_array(raw: str) -> list[dict]:
    """Extract a JSON array from GPT output robustly."""
    # strip markdown fences
    raw = re.sub(r"```(?:json)?", "", raw).strip().rstrip("`").strip()
    try:
        return json.loads(raw)
    except json.JSONDecodeError:
        # try to find the first [...] block
        m = re.search(r"\[.*\]", raw, re.DOTALL)
        if m:
            try:
                return json.loads(m.group(0))
            except Exception:
                pass
    return []


def generate_correction_examples(tool: str, help_text: str, n: int) -> list[dict]:
    if not help_text:
        return []
    prompt = CORRECTION_GEN_PROMPT.format(
        tool=tool, help_text=help_text[:2000], n=n
    )
    try:
        raw = _gpt(prompt, max_tokens=3000)
        items = _parse_json_array(raw)
    except Exception:
        return []

    results = []
    for item in items:
        if not all(k in item for k in ("bad_command", "stderr", "thought", "corrected")):
            continue
        user_content = (
            f"Tool: {tool}\n"
            f"Command attempted: {item['bad_command']}\n\n"
            f"Error output:\n{item['stderr']}\n\n"
            f"Tool help (excerpt):\n{help_text[:800]}\n\n"
            f"Fix this command."
        )
        asst_content = (
            f"<thought>{item['thought']}</thought>\n\n"
            f"<corrected>{item['corrected']}</corrected>"
        )
        results.append({
            "type": "correction",
            "tool": tool,
            "mistake_type": item.get("mistake_type", "unknown"),
            "messages": [
                {"role": "system",    "content": SYSTEM_CORRECTION},
                {"role": "user",      "content": user_content},
                {"role": "assistant", "content": asst_content},
            ],
        })
    return results


def generate_filtering_examples(tool: str, n: int) -> list[dict]:
    use_case = TOOL_USE_CASES.get(tool, "security scanning")
    prompt = FILTERING_GEN_PROMPT.format(tool=tool, use_case=use_case, n=n)
    try:
        raw = _gpt(prompt, max_tokens=3000)
        items = _parse_json_array(raw)
    except Exception:
        return []

    results = []
    for item in items:
        if not all(k in item for k in ("raw_output", "filtered_findings", "summary")):
            continue
        user_content = (
            f"Tool: {tool}\n"
            f"Raw output:\n```\n{item['raw_output']}\n```\n\n"
            f"Extract the findings. Strip progress bars, ANSI codes, repeated headers, and noise."
        )
        asst_content = (
            f"FINDINGS:\n{item['filtered_findings']}\n\n"
            f"SUMMARY: {item['summary']}"
        )
        results.append({
            "type": "filtering",
            "tool": tool,
            "messages": [
                {"role": "system",    "content": SYSTEM_FILTERING},
                {"role": "user",      "content": user_content},
                {"role": "assistant", "content": asst_content},
            ],
        })
    return results


# ---------------------------------------------------------------------------
# I/O helpers
# ---------------------------------------------------------------------------
def load_existing(path: str) -> set[str]:
    """Return set of (type, tool) strings already written."""
    seen = set()
    p = Path(path)
    if not p.exists():
        return seen
    for line in p.read_text().splitlines():
        try:
            d = json.loads(line)
            seen.add(f"{d.get('type','')}::{d.get('tool','')}")
        except Exception:
            pass
    return seen


def count_by_type(path: str) -> dict[str, int]:
    counts: dict[str, int] = {}
    p = Path(path)
    if not p.exists():
        return counts
    for line in p.read_text().splitlines():
        try:
            d = json.loads(line)
            t = d.get("type", "unknown")
            counts[t] = counts.get(t, 0) + 1
        except Exception:
            pass
    return counts


write_lock = threading.Lock()


def append_jsonl(path: str, examples: list[dict]) -> int:
    if not examples:
        return 0
    with write_lock:
        with open(path, "a") as f:
            for ex in examples:
                f.write(json.dumps(ex) + "\n")
    return len(examples)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--test",            action="store_true")
    parser.add_argument("--test-n",          type=int, default=2)
    parser.add_argument("--list-categories", action="store_true")
    parser.add_argument("--type",            choices=["correction", "filtering", "both"], default="both")
    parser.add_argument("--workers",         type=int, default=DEFAULT_WORKERS)
    parser.add_argument("--out-correction",  default=OUTPUT_CORRECTION)
    parser.add_argument("--out-filtering",   default=OUTPUT_FILTERING)
    args = parser.parse_args()

    installed = detect_installed_tools()
    not_installed = [t for t in PENTEST_TOOLS if t not in installed]

    if args.list_categories:
        print(f"\n{'Tool':<20} {'Installed':<12} {'Help?':<8}")
        print("-" * 42)
        for t in PENTEST_TOOLS:
            inst  = t in installed
            help_ = Path(CACHE_DIR, f"{t}.help").exists() if inst else False
            print(f"  {t:<18} {'yes' if inst else 'no':<12} {'cached' if help_ else ''}")
        print(f"\nInstalled: {len(installed)} / {len(PENTEST_TOOLS)}")
        print(f"Correction file: {count_by_type(args.out_correction)}")
        print(f"Filtering  file: {count_by_type(args.out_filtering)}")
        return

    # ── TEST MODE ────────────────────────────────────────────────────────────
    if args.test:
        print("=" * 70)
        print("TEST MODE — source10_executor  (no file writes)")
        print("=" * 70)

        print(f"\nDetected {len(installed)} installed tools: {installed}")
        print(f"Missing:  {not_installed[:10]}{'...' if len(not_installed) > 10 else ''}")

        sample_tools = installed[:args.test_n] if installed else ["curl"]
        for tool in sample_tools:
            print(f"\n{'─'*60}")
            print(f"TOOL: {tool}")
            help_text = fetch_help(tool)
            print(f"  Help length : {len(help_text)} chars")
            print(f"  Help preview: {help_text[:200]!r}")

            print(f"\n  [A] Generating {args.test_n} correction example(s)...")
            corr = generate_correction_examples(tool, help_text, args.test_n)
            if corr:
                ex = corr[0]
                print(f"  Mistake type: {ex.get('mistake_type')}")
                print(f"  User msg    : {ex['messages'][1]['content'][:300]!r}")
                print(f"  Asst msg    : {ex['messages'][2]['content'][:300]!r}")
            else:
                print("  FAILED to generate correction examples")

            print(f"\n  [B] Generating {args.test_n} filtering example(s)...")
            filt = generate_filtering_examples(tool, args.test_n)
            if filt:
                ex = filt[0]
                print(f"  User msg    : {ex['messages'][1]['content'][:300]!r}")
                print(f"  Asst msg    : {ex['messages'][2]['content'][:300]!r}")
            else:
                print("  FAILED to generate filtering examples")

        print("\n" + "=" * 70)
        print("TEST COMPLETE — run without --test to generate full dataset")
        return

    # ── FULL RUN ─────────────────────────────────────────────────────────────
    Path(args.out_correction).parent.mkdir(parents=True, exist_ok=True)

    if not installed:
        print("No pentest tools detected in PATH. Install tools first.")
        return

    print(f"Found {len(installed)} installed tools. Generating training data...")
    total_written = 0

    def _worker_correction(tool: str) -> int:
        help_text = fetch_help(tool)
        if not help_text:
            return 0
        examples = generate_correction_examples(tool, help_text, EXAMPLES_PER_TOOL)
        return append_jsonl(args.out_correction, examples)

    def _worker_filtering(tool: str) -> int:
        examples = generate_filtering_examples(tool, FILTER_PER_TOOL)
        return append_jsonl(args.out_filtering, examples)

    if args.type in ("correction", "both"):
        corr_counts = count_by_type(args.out_correction)
        existing = corr_counts.get("correction", 0)
        remaining_tools = installed if existing < TARGET_CORRECTION else []
        print(f"\n[A] Correction  {existing}/{TARGET_CORRECTION} done")
        with ThreadPoolExecutor(max_workers=args.workers) as ex:
            futs = {ex.submit(_worker_correction, t): t for t in remaining_tools}
            for fut in tqdm(as_completed(futs), total=len(futs), desc="correction"):
                total_written += fut.result()

    if args.type in ("filtering", "both"):
        filt_counts = count_by_type(args.out_filtering)
        existing = filt_counts.get("filtering", 0)
        remaining_tools = installed if existing < TARGET_FILTERING else []
        print(f"\n[B] Filtering   {existing}/{TARGET_FILTERING} done")
        with ThreadPoolExecutor(max_workers=args.workers) as ex:
            futs = {ex.submit(_worker_filtering, t): t for t in remaining_tools}
            for fut in tqdm(as_completed(futs), total=len(futs), desc="filtering"):
                total_written += fut.result()

    print(f"\nWrote {total_written} new examples total")
    print(f"  Correction: {args.out_correction}")
    print(f"  Filtering:  {args.out_filtering}")


if __name__ == "__main__":
    main()
