#!/usr/bin/env python3
"""
Router Classifier Training Script

Trains a lightweight prompt→adapter classifier using:
  - Encoder: sentence-transformers/all-MiniLM-L6-v2 via HuggingFace transformers
    (80MB, CPU-friendly, no GPU needed)
  - Head: 2-layer MLP (384 → 128 → ReLU → num_adapters)
  - Loss: cross-entropy
  - Training: ~5 epochs, ~2 minutes on CPU

Input:  raw/router_labels.jsonl  (generated by src/source14_router.py)
Output: adapters/router_classifier/
          model.pt          — MLP head weights
          label_map.json    — adapter name ↔ class index
          encoder_name.txt  — encoder model name for loading at inference
          stats.json        — per-class accuracy on held-out eval set

Usage:
  python3 src/train_router_classifier.py
  python3 src/train_router_classifier.py --epochs 10 --eval-only
  python3 src/train_router_classifier.py --data raw/router_labels.jsonl
"""

import json
import random
import argparse
import math
from pathlib import Path
from collections import Counter

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader

# ── Config ────────────────────────────────────────────────────────────────────

DATA_PATH   = Path("raw/router_labels.jsonl")
OUTPUT_DIR  = Path("adapters/router_classifier")
ENCODER_NAME = "sentence-transformers/all-MiniLM-L6-v2"
EMBED_DIM   = 384
HIDDEN_DIM  = 128
EPOCHS      = 8
BATCH_SIZE  = 64
LR          = 3e-4
EVAL_SPLIT  = 0.15
SEED        = 42
CONF_THRESHOLD = 0.70  # minimum confidence for classifier to override regex

# ── Mean pooling for CLS-less models ─────────────────────────────────────────

def mean_pool(token_embeddings: torch.Tensor, attention_mask: torch.Tensor) -> torch.Tensor:
    mask = attention_mask.unsqueeze(-1).float()
    return (token_embeddings * mask).sum(1) / mask.sum(1).clamp(min=1e-9)


# ── MLP head ──────────────────────────────────────────────────────────────────

class RouterHead(nn.Module):
    def __init__(self, in_dim: int, hidden: int, num_classes: int) -> None:
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(in_dim, hidden),
            nn.ReLU(),
            nn.Dropout(0.1),
            nn.Linear(hidden, num_classes),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.net(x)


# ── Dataset ───────────────────────────────────────────────────────────────────

class RouterDataset(Dataset):
    def __init__(self, prompts: list[str], labels: list[int]) -> None:
        self.prompts = prompts
        self.labels  = labels

    def __len__(self) -> int:
        return len(self.prompts)

    def __getitem__(self, idx: int) -> tuple[str, int]:
        return self.prompts[idx], self.labels[idx]


# ── Encode in batches ─────────────────────────────────────────────────────────

def encode_batches(
    texts: list[str],
    tokenizer,
    encoder: nn.Module,
    device: torch.device,
    batch_size: int = 64,
    max_length: int = 128,
) -> torch.Tensor:
    all_embeddings = []
    encoder.eval()
    with torch.no_grad():
        for i in range(0, len(texts), batch_size):
            batch = texts[i : i + batch_size]
            enc = tokenizer(
                batch,
                padding=True,
                truncation=True,
                max_length=max_length,
                return_tensors="pt",
            ).to(device)
            out = encoder(**enc)
            emb = mean_pool(out.last_hidden_state, enc["attention_mask"])
            all_embeddings.append(emb.cpu())
    return torch.cat(all_embeddings, dim=0)


# ── Main ──────────────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--data",       default=str(DATA_PATH))
    parser.add_argument("--output",     default=str(OUTPUT_DIR))
    parser.add_argument("--epochs",     type=int,   default=EPOCHS)
    parser.add_argument("--batch-size", type=int,   default=BATCH_SIZE)
    parser.add_argument("--lr",         type=float, default=LR)
    parser.add_argument("--eval-only",  action="store_true",
                        help="Only run evaluation on existing model (skip training)")
    args = parser.parse_args()

    random.seed(SEED)
    torch.manual_seed(SEED)

    out_dir = Path(args.output)

    # ── Load data ────────────────────────────────────────────────────────────
    data_path = Path(args.data)
    if not data_path.exists():
        print(f"[ERROR] Data file not found: {data_path}")
        print("  Run: python3 src/source14_router.py")
        return

    rows = [json.loads(l) for l in data_path.read_text().splitlines() if l.strip()]
    print(f"Loaded {len(rows)} examples from {data_path}")

    # Build label map
    adapters = sorted(set(r["adapter"] for r in rows))
    label_map = {a: i for i, a in enumerate(adapters)}
    inv_label_map = {i: a for a, i in label_map.items()}
    num_classes = len(adapters)
    print(f"Classes ({num_classes}): {adapters}")

    # Count distribution
    dist = Counter(r["adapter"] for r in rows)
    print("\nPer-class distribution:")
    for a in adapters:
        bar = "█" * (dist[a] // 20)
        print(f"  {a:<12} {dist[a]:>5}  {bar}")

    prompts = [r["prompt"] for r in rows]
    labels  = [label_map[r["adapter"]] for r in rows]

    # Train / eval split
    indices = list(range(len(prompts)))
    random.shuffle(indices)
    split_idx = int(len(indices) * (1 - EVAL_SPLIT))
    train_idx = indices[:split_idx]
    eval_idx  = indices[split_idx:]

    train_prompts = [prompts[i] for i in train_idx]
    train_labels  = [labels[i]  for i in train_idx]
    eval_prompts  = [prompts[i] for i in eval_idx]
    eval_labels   = [labels[i]  for i in eval_idx]

    print(f"\nTrain: {len(train_prompts)}  |  Eval: {len(eval_prompts)}")

    # ── Load encoder ─────────────────────────────────────────────────────────
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"\nDevice: {device}")
    print(f"Loading encoder: {ENCODER_NAME}")

    from transformers import AutoTokenizer, AutoModel
    tokenizer = AutoTokenizer.from_pretrained(ENCODER_NAME)
    encoder   = AutoModel.from_pretrained(ENCODER_NAME).to(device)
    encoder.eval()
    for p in encoder.parameters():
        p.requires_grad_(False)

    # ── Pre-encode all prompts ────────────────────────────────────────────────
    print("Encoding training prompts...")
    train_emb = encode_batches(train_prompts, tokenizer, encoder, device)
    print("Encoding eval prompts...")
    eval_emb  = encode_batches(eval_prompts,  tokenizer, encoder, device)

    # ── Build MLP head ────────────────────────────────────────────────────────
    head = RouterHead(EMBED_DIM, HIDDEN_DIM, num_classes).to(device)

    if args.eval_only:
        model_path = out_dir / "model.pt"
        if not model_path.exists():
            print(f"[ERROR] No model at {model_path}. Train first.")
            return
        head.load_state_dict(torch.load(model_path, map_location=device))
        print(f"Loaded model from {model_path}")
    else:
        # ── Training loop ─────────────────────────────────────────────────────
        optimizer = optim.AdamW(head.parameters(), lr=args.lr)
        criterion = nn.CrossEntropyLoss()

        train_dataset = RouterDataset(
            list(range(len(train_emb))), train_labels
        )
        loader = DataLoader(train_dataset, batch_size=args.batch_size, shuffle=True)

        print(f"\nTraining MLP head — {args.epochs} epochs, lr={args.lr}")
        for epoch in range(1, args.epochs + 1):
            head.train()
            total_loss = 0.0
            correct = 0
            for idx_batch, lbl_batch in loader:
                emb_batch = train_emb[idx_batch].to(device)
                lbl_batch = torch.tensor(lbl_batch).to(device)

                optimizer.zero_grad()
                logits = head(emb_batch)
                loss   = criterion(logits, lbl_batch)
                loss.backward()
                optimizer.step()

                total_loss += loss.item() * len(lbl_batch)
                correct    += (logits.argmax(1) == lbl_batch).sum().item()

            avg_loss = total_loss / len(train_prompts)
            train_acc = correct / len(train_prompts)
            print(f"  Epoch {epoch}/{args.epochs}  loss={avg_loss:.4f}  train_acc={train_acc:.3f}")

    # ── Evaluation ─────────────────────────────────────────────────────────────
    head.eval()
    with torch.no_grad():
        logits = head(eval_emb.to(device))
        probs  = torch.softmax(logits, dim=1)
        preds  = logits.argmax(1).cpu().tolist()
        confs  = probs.max(1).values.cpu().tolist()

    eval_labels_t = torch.tensor(eval_labels)
    overall_acc   = sum(p == l for p, l in zip(preds, eval_labels)) / len(eval_labels)

    # Per-class accuracy
    class_correct = Counter()
    class_total   = Counter()
    for pred, label in zip(preds, eval_labels):
        class_total[label] += 1
        if pred == label:
            class_correct[label] += 1

    # Confidence-gated accuracy (only count examples where conf >= threshold)
    gated_preds  = [(p, l) for p, l, c in zip(preds, eval_labels, confs) if c >= CONF_THRESHOLD]
    gated_acc    = sum(p == l for p, l in gated_preds) / max(1, len(gated_preds))
    gated_pct    = len(gated_preds) / len(eval_labels) * 100

    print(f"\n{'─'*55}")
    print(f"  Overall eval accuracy  : {overall_acc:.3f} ({100*overall_acc:.1f}%)")
    print(f"  Gated  (conf>={CONF_THRESHOLD:.2f})     : {gated_acc:.3f} ({100*gated_acc:.1f}%)  "
          f"[{len(gated_preds)}/{len(eval_labels)} = {gated_pct:.0f}% of eval examples triggered classifier]")
    print(f"\n  Per-class accuracy:")
    per_class_stats = {}
    for idx, adapter in inv_label_map.items():
        total = class_total[idx]
        correct = class_correct[idx]
        acc = correct / total if total else 0.0
        bar = "█" * int(acc * 20)
        print(f"    {adapter:<12} {correct:>4}/{total:<4}  {100*acc:5.1f}%  {bar}")
        per_class_stats[adapter] = {"correct": correct, "total": total, "accuracy": round(acc, 4)}
    print(f"{'─'*55}\n")

    # ── Save ──────────────────────────────────────────────────────────────────
    if not args.eval_only:
        out_dir.mkdir(parents=True, exist_ok=True)
        torch.save(head.state_dict(), out_dir / "model.pt")

        (out_dir / "label_map.json").write_text(json.dumps(label_map, indent=2))
        (out_dir / "encoder_name.txt").write_text(ENCODER_NAME)
        (out_dir / "stats.json").write_text(json.dumps({
            "overall_accuracy": round(overall_acc, 4),
            "gated_accuracy":   round(gated_acc,   4),
            "gated_coverage_pct": round(gated_pct, 1),
            "conf_threshold":   CONF_THRESHOLD,
            "encoder":          ENCODER_NAME,
            "embed_dim":        EMBED_DIM,
            "hidden_dim":       HIDDEN_DIM,
            "num_classes":      num_classes,
            "train_examples":   len(train_prompts),
            "eval_examples":    len(eval_prompts),
            "per_class":        per_class_stats,
        }, indent=2))

        print(f"Model saved to {out_dir}/")
        print(f"  model.pt        — MLP head weights")
        print(f"  label_map.json  — adapter ↔ class index")
        print(f"  encoder_name.txt — {ENCODER_NAME}")
        print(f"  stats.json      — evaluation metrics")
        print(f"\nTo use in production:")
        print(f"  router.load_classifier('{out_dir}')")


if __name__ == "__main__":
    main()
